SYSTEM:
  phase: 'train'
  num_run: 1
  device: "cuda:0" # "cuda:0"; "cuda:1"; "cpu"
  gpus: [0, 1]
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
  neptune:
    use: true
DATASET:
  name: 'avenue'
  
  read_format: 'PIL' # PIL, CV2
  image_format: 'jpg'
  
  width: 256
  height: 256
  channel: 3
  normalized: true
  
  num_frames: 5 # 5 for prediction, 1 for reconstruction
  frame_steps: 1
  # (3,256,256) => cat => (15,256,256)
  # (3,256,256) => stack => (5,3,256,256)
  clip_mode: 'cat' # cat, stack, list
  clip_dim: 0
  skip_frames: [2,3,4,5]
  
  train:
    train_set: 'training_22'
    batch_size_per_gpu: 4
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: true
    sample_type: 'clips' #  'videos', 'clips', 'clips_by_video'

  test:
    test_set: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'avenue.mat'
    sample_type: 'videos' # videos', 'clips_by_video'
    
MODEL:
  name: 'MNAD_woMem'
  type: 'prediction'
  method: 'MNAD_woMem'
  
TRAIN:
  name: 'mnad_trainer'
  begin_epoch: 0
  end_epoch: 60
  save_freq: 5
  resume: false # false, true
  dir_name: 'session_2023_12_04_19_45_45'  # 'session_2023_12_25_22_44_1'
  file_name: 'epoch_45.pth'  # 'epoch_1.pth'
  
  optimizer:
    name: 'Adam'
    lr: 2e-4  #0.0002
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0  # Adam, SGD, RMSprop

    momentum: 0.0  # SGD, RMSprop
    nesterov: false  # SGD
    rmsprop_alpha: 0.99  # RMSprop
    rmsprop_centered: false  # RMSprop
    
  lr_scheduler:
    use: true
    name: 'CosineAnnealingLR'
    step_size: 20 # for StepLR
    milestones: [20, 40] # for MultiStepLR
    gamma: 0.1  # for StepLR, MultiStepLR
    eta_min: 0.0 # Minimum learning rate for 'CosineAnnealingLR'
  
  other_params:
    feature_dim: 512
    memory_dim: 512
    memory_size: 10
    
    loss_compact: 0.1
    loss_separate: 0.1
TEST:
  name: 'mnad_tester'
  dir_name: 'session_2023_12_10_13_21'
  file_name: 'epoch_60.pth'
  plot_types: ['none']   # 'none', 'gif', 'video', 'csv'
  plot_video_ids: [0]   # list of selected video_ids (>=1) to plot, [-1] for all, [0] for none
  train_batch_size_per_gpu: 4
  psnr_types: ['psnr_1', 'psnr_frame'] # 'psnr_max', 'psnr_frame', 'psnr_1', 'psnr_patch'

  other_params:
    ano_score_alpha: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
    update_threshold: 0.01



