SYSTEM:
  phase: 'train'
  num_run: 1
  device: "cuda:0" # "cuda:0"; "cuda:1"; "cpu"
  gpus: [0, 1]
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
  neptune:
    use: true
DATASET:
  name: 'avenue'
  
  read_format: 'CV2' # PIL, CV2
  image_format: 'jpg'
  
  width: 256
  height: 256
  channel: 1
  normalized: true
  
  num_frames: 16 #
  frame_steps: 1
  clip_mode: 'stack' # cat, stack, list
  clip_dim: 1

  dict_sf:
    p: 0.01
    s: [ 2,3,4,5 ]
  
  train:
    train_set: 'training'
    batch_size_per_gpu: 4
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: true
    sample_type: 'clips' #  'videos', 'clips', 'clips_by_video'
    
  test:
    test_set: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'ped2.mat'
    sample_type: 'videos' # videos', 'clips_by_video'
    
MODEL:
  name: 'STEAL'
  type: 'reconstruction'
  alias: 'STEAL'
  
TRAIN:
  name: 'steal_trainer'
  begin_epoch: 0
  end_epoch: 60
  save_freq: 5
  resume: false # false, true
  dir_name: 'session_2023_12_04_19_45_45'  # 'session_2023_12_25_22_44_1'
  file_name: 'epoch_45.pth'  # 'epoch_1.pth'

  optimizer:
    name: 'Adam'
    lr: 1e-4  #0.0001
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0  # Adam, SGD, RMSprop

    momentum: 0.0  # SGD, RMSprop
    nesterov: false  # SGD
    rmsprop_alpha: 0.99  # RMSprop
    rmsprop_centered: false  # RMSprop
    
  lr_scheduler:
    use: false
    name: 'MultiStepLR' # # LinearLR, StepLR, MultiSetpLR, CosineAnnealingLR
    step_size: 20 # for StepLR
    milestones: [20, 40] # for MultiStepLR
    gamma: 0.1  # for StepLR, MultiStepLR
    eta_min: 0.0 # Minimum learning rate for 'CosineAnnealingLR'

TEST:
  name: 'steal_tester'
  dir_name: 'session_2024_02_10_10_04'
  file_name: 'epoch_60.pth'
  train_batch_size_per_gpu: 4
  psnr_types: ['psnr_max'] # 'psnr_max', 'psnr_1'

  # lr_scheduler: false
  # session_2024_02_10_10_04: p=0.01,bz=4,epoch=60,AUC: AUC: 85.09
 

