SYSTEM:
  phase: 'train'
  device: "cuda:0" # "cuda:0"; "cuda:1"; "cpu"
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
  neptune:
    use: true
DATASET:
  name: 'avenue'
  
  read_format: 'PIL' # opencv
  image_format: 'jpg'
  
  width: 256
  height: 256
  channel: 3
  normalized: true
  
  num_frames: 5 # 5 for prediction, 1 for reconstruction
  frame_steps: 1
  clip_mode: 'cat' # cat, stack, list
  clip_dim: 0
  skip_frames: [2,3,4,5]
  
  train:
    train_set: 'training'
    batch_size_per_gpu: 4
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: true
    sample_type: 'clips' #  'videos', 'clips', 'clips_by_video'
    # 'training_keyframes_DeepKmean_0.30'; 
    # 'training_keyframes_op_0.30'
    # 'training_keyframes_Entropy_0.30'
    keyframes_dir: 'training_keyframes_op_0.30'
    
  test:
    test_set: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'avenue.mat'
    sample_type: 'videos' # videos', 'clips_by_video'
    
MODEL:
  name: 'PAMAE5'
  type: 'prediction'
  
TRAIN:
  name: 'pamae_trainer'
  begin_epoch: 0
  end_epoch: 60
  save_freq: 5
  resume: false # false, true
  dir_name: 'session_2023_12_28_21_56'
  file_name: 'epoch_40.pth'

  optimizer:
    name: 'Adam'
    lr: 2e-4  #0.0002
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0  # Adam, SGD, RMSprop

    momentum: 0.0  # SGD, RMSprop
    nesterov: false  # SGD
    rmsprop_alpha: 0.99  # RMSprop
    rmsprop_centered: false  # RMSprop
    
  lr_scheduler:
    use: true
    name: 'CosineAnnealingLR'
    step_size: 20 # for StepLR
    milestones: [20, 40] # for MultiStepLR
    gamma: 0.1  # for StepLR, MultiStepLR
    eta_min: 0.0 # Minimum learning rate for 'CosineAnnealingLR'
  
  other_params:
    feature_dim: 512
    memory_dim: 512
    memory_size: 10
    
    skip_frames_prob: 0.01
    loss_compact: 0.1
    loss_separate: 0.1
    print_seq: 1000
TEST:
  name: 'pamae_tester'
  dir_name: 'session_2023_12_30_23_45'
  # Deep K-mean: session_2023_12_06_17_17: p=0.002,bz=4,epoch=60; Best AUC=85.12 alpha=0.3 
  # Deep K-mean: session_2023_12_27_16_49: p=0.01,bz=4,epoch=60; Best AUC=84.12 alpha=0.5
  # Opticalflow (max): session_2023_12_28_21_56: p=0.01,bz=4,epoch=60; Best AUC=83.93 alpha=0.8
  # Opticalflow (max-min): session_2023_12_30_23_45: p=0.01,bz=4,epoch=60; Best AUC=84.79 alpha=0.5

  # Deep K-mean: session_2023_12_06_17_17: p=0.002,bz=4,epoch=45; Best AUC=84.99 alpha=0.5 
  # Deep K-mean: session_2023_12_27_16_49: p=0.01,bz=4,epoch=45; Best AUC=84.96 alpha=0.7 
  # Opticalflow (max): session_2023_12_28_21_56: p=0.01,bz=4,epoch=45; Best AUC=82.98 alpha=0.7
  # Opticalflow (max-min): session_2023_12_30_23_45: p=0.01,bz=4, epoch=45; Best AUC=85.02 alpha=0.4
  file_name: 'epoch_60.pth'
  train_batch_size_per_gpu: 4

  other_params:
    ano_score_alpha: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
    update_threshold: 0.01

