SYSTEM:
  phase: 'train'
  loop_index: 1
  gpus: (0,1) # (0,1), (0,), (1,)
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
DATASET:
  name: 'ped2'
  
  read_format: 'PIL' # opencv
  image_format: 'jpg'
  
  width: 64
  height: 64
  channel: 3
  
  num_frames: 1
  frame_steps: 1
  lower_bound: 100
  
  train:
    trainset: 'training'
    batch_size_per_gpu: 4
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: true

  test:
    testset: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'ped2.mat'
    
MODEL:
  name: 'Diffusion2'
  type: 'prediction'
  
TRAIN:
  name: 'pamae_trainer'
  begin_epoch: 0
  end_epoch: 60
  save_freq: 5
  resume: false # false, true
  checkpoint_filepath: './output/train/MNAD/ped2/001-2023-08-07-18-31/checkpoint/epoch_10.pth'
  
  losses: ['loss_RecLoss_cuda', 1, 'L2Loss', [], 
          'loss_MemLoss_cuda', 0.0002, 'MemLoss', []]
  
  optimizer:
    name: 'Adam'
    learning_rate: 3e-4
    
  lr_scheduler:
    use: true
    name: 'MultiStepLR'
    step_size: 1000
    steps: [63800, 127600]
    gamma: 0.1
  
  other_params:
    feature_dim: 512
    memory_dim: 512
    memory_size: 10
    skip_frames: (2,3,4,5)
    skip_frames_prob: 0.0
    patch_prob: 0.0
    noise_prob: 0.0
    fusion_prob: 0.0
    loss_compact: 0.0
    loss_separate: 0.0
  
TEST:
  name: 'pamae_tester'
  checkpoint_filepaths: [
      './output/train/Diffusion2/ped2/001-0.0-2023-08-15-15-26/checkpoint/epoch_45.pth'
                          ]
  other_params:
    ano_score_alpha: [0.6, 0.7, 0.8, 0.9, 1.0]
    update_threshold: 0.01

