SYSTEM:
  phase: 'train'
  num_run: 1
  device: "cuda:0" # "cuda:0"; "cuda:1"; "cpu"
  gpus: [0, 1]
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
  neptune:
    use: true
DATASET:
  name: 'avenue'
  
  read_format: 'PIL' # PIL, CV2
  image_format: 'jpg'
  
  width: 256
  height: 256
  channel: 3
  normalized: true
  
  num_frames: 5 # 5 for prediction, 1 for reconstruction
  frame_steps: 1
  # (3,256,256) => cat => (15,256,256)
  # (3,256,256) => stack => (5,3,256,256)
  clip_mode: 'cat' # cat, stack, list
  clip_dim: 0

  dict_sf:
    p: 0.0  # xac suat skip_frames: 0.01, 0.005
    s: [2,3,4,5]  # so luong skip_frames, lay ngau nhien trong [2,..5]

  dict_kf:
    p: 0.002  # xac suat key_frames: 0.01, 0.005, 0.002

  dict_patch:
    p: 0.0  # xac suat add patch vao frames
    alpha: 0.5  # control the maximum size of the patch relative to the frame size: posW and posH= random in [10,alphaW] and [10,alphaH]
    beta: 25  # adjust the maximum movement of the patch in terms of pixels: new_pos= (center_pos + random in [-beta,beta])
    technique: 'SmoothMixS'
    intruder: 'CIFAR-100'

  dict_shake:
    p: 0.0  # xac suat rung lac camera
    rot: [1,3]  # degree for rotation
    trans: [0.01,0.02]  # percentage pixels for translation
  
  train:
    train_set: 'training'
    batch_size_per_gpu: 4
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: true
    sample_type: 'clips' #  'videos', 'clips', 'clips_by_video'
    # training_KF_OF_30: 'training_keyframes_op_0.30'
    # training_KF_KM_30: 'training_keyframes_DeepKmean_0.30';
    # training_KF_GA_30: 'training_keyframes_Entropy_0.30'
    # training_KF_ES_30: (key frames with entropy sorted)
    # training_KF_EM: (key frames with entropy medium)
    # training_KF_EN: (key frames with entropy medium no adjacent)
    keyframes_dir: 'training_KF_OF_30'

  test:
    test_set: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'avenue.mat'
    sample_type: 'videos' # videos', 'clips_by_video'
    
MODEL:
  name: 'PAMAE_woMem'
  type: 'prediction'
  method: 'PAMAE_woMem_KF_OF'
  # PAMAE_woMem_SF (Skip Frames): p_sf=0.01
  # PAMAE_woMem_KF_OF (Key Frames with Optical Flow): p_kf=0.01
  # PAMAE_woMem_KF_KM (Key Frames with K-Mean)
  # PAMAE_woMem_KF_ES (Key Frames with Entropy Sorted)
  # PAMAE_woMem_KF_EM (Key Frames with Entropy Medium)
  # PAMAE_woMem_KF_EN (Key Frames with Entropy medium No adjacent)
  # PAMAE_woMem_SF_KF (Skip Frames with Key Frames): p_sf=0.005, p_kf=0.005
  
TRAIN:
  name: 'pamae_trainer'
  begin_epoch: 0
  end_epoch: 60
  save_freq: 5
  resume: false # false, true
  dir_name: 'session_2024_02_24_21_52'
  checkpoint_source: 'session_2024_02_21_00_21'
  checkpoint_destination: 'session_2024_02_17_00_01'
  file_name: 'epoch_39.pth'
  
  optimizer:
    name: 'Adam'
    lr: 2e-4  #0.0002
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0  # Adam, SGD, RMSprop

    momentum: 0.0  # SGD, RMSprop
    nesterov: false  # SGD
    rmsprop_alpha: 0.99  # RMSprop
    rmsprop_centered: false  # RMSprop
    
  lr_scheduler:
    use: true
    name: 'CosineAnnealingLR'
    step_size: 20 # for StepLR
    milestones: [20, 40] # for MultiStepLR
    gamma: 0.1  # for StepLR, MultiStepLR
    eta_min: 0.0 # Minimum learning rate for 'CosineAnnealingLR'
  
  other_params:
    feature_dim: 512
    memory_dim: 512
    memory_size: 10
    
    loss_compact: 0.1
    loss_separate: 0.1
    print_seq: 1000
TEST:
  name: 'pamae_tester'
  dir_name: 'session_2024_02_24_21_52'
  file_name: 'epoch_60.pth'
  plot_types: ['none']   # 'none', 'gif', 'video', 'csv'
  plot_video_ids: [0]   # list of selected video_ids (>=1) to plot, [-1] for all, [0] for none
  train_batch_size_per_gpu: 4
  psnr_types: ['psnr_1', 'psnr_frame'] # 'psnr_max', 'psnr_frame', 'psnr_1', 'psnr_patch'

  other_params:
    ano_score_alpha: [ 1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0 ]
    update_threshold: 0.01

    # =================================
    # PAMAE_woMem_KF_OF (Key frames with Optical flow)
    # =================================
    # p=0.01,bz=4,epoch=60; 
    # session_2024_02_28_10_28: (server1) best_AUC=83.52
    # session_2024_03_01_17_59: (RTX3060) best_AUC=83.01

    # =================================
    # p=0.002,bz=4,epoch=60; VideoDataset_kf()
    # session_2024_03_02_16_59 (GPU2):
      # epoch_10.pth: best_AUC=84.97

    # =================================
    # p=0.002,bz=4,epoch=60; VideoDataset()
    # session_2024_03_06_13_33:
      # epoch_10.pth: best_AUC=84.53




    
        