SYSTEM:
  phase: 'train' # 'preprocess_training', 'preprocess_testing', 'train_DAE', 'train_GMM', 'evaluate'
  device: "cuda:0" # "cuda:0"; "cuda:1"; "cpu"
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  output:
    log_dir: 'log'
    tesorboard_dir: 'tensorboard'
    checkpoint_dir: 'checkpoint'
    visualization_dir: 'visualization'
DATASET:
  name: 'ped2'
  
  read_format: 'PIL' # opencv
  image_format: 'jpg'
  
  width: 64
  height: 64
  channel: 1
  normalized: true
  
  num_frames: 1 # 5 for prediction, 1 for reconstruction
  frame_steps: 1
  clip_mode: 'list' # cat, stack, list
  clip_dim: 0
  weights_yolov5: 'libs/pytorch_yolov5/weights/yolov5s.pt'
  train:
    train_set: 'training'
    batch_size_per_gpu_DAE: 500
    batch_size_per_gpu_GMM: 1000
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: false
    sample_type: 'clips' #  'videos', 'clips', 'clips_by_video'
    train_set_Img: 'training_Crop_Img'
    train_set_Dimg: 'training_Crop_Dimg'

  test:
    test_set: 'testing'
    batch_size_per_gpu: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false
    gt_filename: 'ped2.mat'
    sample_type: 'videos' # videos', 'clips_by_video'
    label_filename: 'frame_labels_ped2.npy'
    
MODEL:
  name: 'GMM_DAE'
  type: 'reconstruction'
  
TRAIN:
  name: 'GMM_DAE_trainer'
  begin_epoch: 0
  end_epoch: 100
  save_freq: 50
  resume: false # false, true
  dir_name: 'session_2023_12_04_19_45_45'  # 'session_2023_12_25_22_44_1'
  file_name: 'epoch_45.pth'  # 'epoch_1.pth'
  
  optimizer:
    name: 'Adam'
    lr: 0.01
    betas: [ 0.9, 0.999 ]
    eps: 1e-8
    weight_decay: 0.0001  # Adam, SGD, RMSprop

    momentum: 0.0  # SGD, RMSprop
    nesterov: false  # SGD
    rmsprop_alpha: 0.99  # RMSprop
    rmsprop_centered: false  # RMSprop
    
  lr_scheduler:
    use: true
    name: 'StepLR'
    step_size: 25 # ('StepLR')
    milestones: [20, 40] # for MultiStepLR
    gamma: 0.6 # 'StepLR', 'MultiStepLR'
    eta_min: 0.0 # Minimum learning rate ('CosineAnnealingLR')
  
  other:
    gmm_components: 15
    
TEST:
  name: 'GMM_DAE_tester'
  checkpoint_DAE_Img: './output/train_DAE/GMM_DAE/ped2/001_100_2023_12_07_11_26/checkpoint/Img_final.pt' # './output/train_DAE/GMM_DAE/ped2/001-2023-11-09-22-35/checkpoint/Img_final.pt'
  checkpoint_DAE_Dimg: './output/train_DAE/GMM_DAE/ped2/001_100_2023_12_07_11_26/checkpoint/Dimg_final.pt' # './output/train_DAE/GMM_DAE/ped2/001-2023-11-09-22-35/checkpoint/Dimg_final.pt'
  checkpoint_GMM_Img: './output/train_GMM/GMM_DAE/ped2/001_100_2023_12_07_11_32/checkpoint/Img_GmmTheta.pkl' # './output/train_GMM/GMM_DAE/ped2/001-2023-11-10-00-23/checkpoint/Img_GmmTheta.pkl'
  checkpoint_GMM_Dimg: './output/train_GMM/GMM_DAE/ped2/001_100_2023_12_07_11_32/checkpoint/Dimg_GmmTheta.pkl' # './output/train_GMM/GMM_DAE/ped2/001-2023-11-10-00-23/checkpoint/Dimg_GmmTheta.pkl'
